In [4]:
import numpy as np
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
print(var1 + var2)

[ 6  8 10 12]


In [8]:
var1 = np.array([1,2,3,4])
print(var1)
print()
print(var1.shape)
print()

var2 = np.array([[1,2,3,4],[5,6,7,8],[3,4,5,6]])
print(var2)
print()
print(var2.shape)

print(var1 + var2)

[1 2 3 4]

(4,)

[[1 2 3 4]
 [5 6 7 8]
 [3 4 5 6]]

(3, 4)
[[ 2  4  6  8]
 [ 6  8 10 12]
 [ 4  6  8 10]]


In [11]:
var3 = np.array([[1,2,4],[3,7,9]])
var4 = np.array([[2],[7]])
print(var3)
print()
print(var4)
print()
print(var3.shape)
print()
print(var4.shape)
print()
print(var3 + var4)

[[1 2 4]
 [3 7 9]]

[[2]
 [7]]

(2, 3)

(2, 1)

[[ 3  4  6]
 [10 14 16]]
