ARRAYS


In [4]:
import numpy as np
x=[1,2,3,4]
y = np.array(x)
print(y)
y
print(type(y))
print(y.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [3]:
import numpy as np
l = []
for i in range(1,5):
    int_1 = int(input("enter : "))
    l.append(int_1)

print(np.array(l))


enter : 12
enter : 13
enter : 14
enter : 5
[12 13 14  5]


In [6]:
ar2 = np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [7]:
ar3 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(ar3)
print(ar3.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3


In [9]:
arn = np.array([1,2,3,4],ndmin = 10 )
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
