In [3]:
import numpy as np
var = np.array([1,2,3,4,13,56,32,])
print("Data Type : ",var.dtype)

Data Type :  int64


In [4]:
var = np.array([1.0,2.0,3.0,4.0,13.0,56.0,32.0,])
print("Data Type : ",var.dtype)

Data Type :  float64


In [5]:
var = np.array(['a','b','c','d'])
print("Data Type : ",var.dtype)

Data Type :  <U1


In [6]:
var = np.array(['a','b','c','d',1,2,3,4])
print("Data Type : ",var.dtype)

Data Type :  <U21


In [7]:
x = np.array([1,2,3,4])
print("data typr: ",x.dtype)

data typr:  int64


In [9]:
x = np.array([1,2,3,4],dtype = np.int8)
print("data typr: ",x.dtype)
print(x)

data typr:  int8
[1 2 3 4]


In [10]:
x = np.array([1,2,3,4],dtype = 'f')
print("data typr: ",x.dtype)
print(x)

data typr:  float32
[1. 2. 3. 4.]


In [12]:
x1 = np.array([1,2,3,4])
new = np.float32(x1)
print("data type : ",x1.dtype)
print("data type : ",new.dtype)
print(x1)
print(new)

data type :  int64
data type :  float32
[1 2 3 4]
[1. 2. 3. 4.]
