INDEXING

In [5]:
import numpy as np
x = np.array([1,2,3])
print(x)
print(x[1])
print(x[-2])


[1 2 3]
2
2


In [12]:
x = np.array([[9,6,4],[3,6,9]])
print(x)
print(x[0,1])
print(x.ndim)

[[9 6 4]
 [3 6 9]]
6
2


In [19]:
y = np.array([[[1,2],[5,6]]])
print(y)
print(y.ndim)
print(y[0,1,1])


[[[1 2]
  [5 6]]]
3
6


In [22]:
a = np.array([[[1,3,5],[2,4,6]],[[1,3,5],[2,4,6]]])
print(a)
print(a.ndim)
print(a[1,1,2])

[[[1 3 5]
  [2 4 6]]

 [[1 3 5]
  [2 4 6]]]
3
6


SLICING

In [26]:
a1 = np.array([1,2,3,4,5])
print(a1)
print()
print("from index 1 to 3 : ",a1[1:3])
print("from 1 to end : ",a1[1:])
print("start to 3 : ",a1[:3])
print("stop: ",a1[::2])                  #jumps 1 from btwn

[1 2 3 4 5]

from index 1 to 3 :  [2 3]
from 1 to end :  [2 3 4 5]
start to 3 :  [1 2 3]
stop:  [1 3 5]


In [28]:
b1 = np.array([[1,2,3,4,5],[9,8,7,6,5],[2,4,6,8,10]])
print(b1)
print()
print("8 to 5 : ",b1[1,1:])
print("12 to 15 : ",b1[2,0:3])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [ 2  4  6  8 10]]

8 to 5 :  [8 7 6 5]
12 to 15 :  [2 4 6]
