ITERATION

In [1]:
import numpy as np
var = np.array([9,8,7,6,5,4,3])
print(var)
print()

for i in var :
  print(i)

[9 8 7 6 5 4 3]

9
8
7
6
5
4
3


In [4]:
var = np.array([[1,2,3,4],[5,6,7,8]])
print(var)
print()
for j in var :
  print(j)
print()
for k in var :
  for l in k :
    print(l)


[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]

1
2
3
4
5
6
7
8


In [7]:
c = np.array([[[1,2,3,4],[1,2,3,4]]])
print(c)
print()
for i in c :
  print(i)
print()
for j in c :
  for k in j :
    for l in k :
       print(l)

[[[1 2 3 4]
  [1 2 3 4]]]

[[1 2 3 4]
 [1 2 3 4]]

1
2
3
4
1
2
3
4


In [8]:
c = np.array([[[1,2,3,4],[1,2,3,4]]])
print(c)
print()
for i in np.nditer(c) :
  print(i)

[[[1 2 3 4]
  [1 2 3 4]]]

1
2
3
4
1
2
3
4


In [11]:
c = np.array([[[1,2,3,4],[1,2,3,4]]])
print(c)
print()
for i in np.nditer(c,flags=['buffered'],op_dtypes = ["S"]) : #converts into string by creating buffer
  print(i)

[[[1 2 3 4]
  [1 2 3 4]]]

b'1'
b'2'
b'3'
b'4'
b'1'
b'2'
b'3'
b'4'


In [13]:
c = np.array([[[1,2,3,4],[1,2,3,4]]])
print(c)
print()
for i,d in np.ndenumerate(c) :
  print(i,d)

[[[1 2 3 4]
  [1 2 3 4]]]

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4
