# **JOINING ARRAY**

In [1]:
import numpy as np
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
c = np.concatenate((x,y))
print(c)


[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
a = np.array([[1,2,3,4],[5,6,7,8]])
b = np.array([[9,10,11,12],[13,14,15,16]])
ar_new = np.concatenate((a,b),axis=1)
print(a)
print()
print(b)
print()
print(ar_new)

[[1 2 3 4]
 [5 6 7 8]]

[[ 9 10 11 12]
 [13 14 15 16]]

[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]


In [10]:
import numpy as np
var_1 = np.array([1,2,3,4,5])
var_2= np.array([6,7,8,9,10])

ar_new1 = np.stack((var_1,var_2),axis = 1)     #using stac function joins 2 array with differnt 2 arrays
print(ar_new1)
ar_new2 = np.hstack((var_1,var_2))             #row
ar_new3 = np.vstack((var_1,var_2))             #column vertical
ar_new4 = np.dstack((var_1,var_2))              #height
print()
print(ar_new2)
print()
print(ar_new3)
print()
print(ar_new4)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]

[ 1  2  3  4  5  6  7  8  9 10]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]


# **SPLIT ARRAY**

In [13]:
var = np.array([1,2,3,4,5,6,7,8,9,10])
print(var)
print()
ar_new = np.split(var,5)
print(ar_new)
print(type(ar_new))
print(ar_new[1])

[ 1  2  3  4  5  6  7  8  9 10]

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]
<class 'list'>
[3 4]


In [17]:
var1 = np.array([[1,2,3,4],[5,6,7,8]])
print(var1)
print()
ar_new = np.split(var1,2)
print(ar_new)

[[1 2 3 4]
 [5 6 7 8]]

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
