In [1]:
import numpy as np
var = np.array([1,5,7,3,8])
np.random.shuffle(var)
print(var)

[5 1 8 7 3]


In [5]:
var1 = np.array([1,5,7,5,7,1,7,3,8])
x = np.unique(var1,return_index= True)
print(x)

(array([1, 3, 5, 7, 8]), array([0, 7, 1, 2, 8]))


In [7]:
var_2 = np.array([1,2,3,4,5,6])
y = np.resize(var_2,(2,3))
print(y)

[[1 2 3]
 [4 5 6]]


In [8]:
var_2 = np.array([1,2,3,4,5,6])
y = np.resize(var_2,(2,3))
print(y.flatten())


[1 2 3 4 5 6]


# NUMPY INSERT AND DELETE FUNCTIONS

In [9]:
x = np.array([1,2,3,4,5,6])
y = np.insert(x,2,5)
print(y)

[1 2 5 3 4 5 6]


In [12]:
var_1 = np.array([[1,2,3],[1,2,3]])
v1 = np.insert(var_1,2,6,axis = 0)
print(v1)

[[1 2 3]
 [1 2 3]
 [6 6 6]]


In [13]:
var_1 = np.array([[1,2,3],[1,2,3]])
v1 = np.insert(var_1,2,6,axis = 1)
print(v1)

[[1 2 6 3]
 [1 2 6 3]]


In [15]:
x = np.array([1,2,3,4,5,6])
y = np.append(x,2.5)
print(y)

[1.  2.  3.  4.  5.  6.  2.5]


In [19]:
var_1 = np.array([[1,2,3],[1,2,3]])
v1 = np.append(var_1,[[45,44,6]],axis =0)
print(v1)

[[ 1  2  3]
 [ 1  2  3]
 [45 44  6]]
