In [1]:
import numpy as np
var = np.array([1,2,3,4])
varadd = var + 3
print(varadd)

[4 5 6 7]


In [2]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
varadd = var1 + var2
print(varadd)

[ 6  8 10 12]


In [3]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
varadd = var1 - var2
print(varadd)

[-4 -4 -4 -4]


In [4]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
varadd = var1 * var2
print(varadd)

[ 5 12 21 32]


In [5]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
varadd = var1 / var2
print(varadd)

[0.2        0.33333333 0.42857143 0.5       ]


In [6]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
varadd = var1 % var2
print(varadd)

[1 2 3 4]


In [7]:
var1 = np.array([1,2,3,4])
var2 = np.array([5,6,7,8])
varadd = var1 ** var2
print(varadd)

[    1    64  2187 65536]


In [8]:
var1 = np.array([1,2,3,4])
varadd = np.reciprocal(var1)
print(varadd)

[1 0 0 0]


2D array

In [9]:
var21 = np.array([[1,2,3,4],[5,6,7,8]])
varadd = np.add(var21,3)
print(varadd)

[[ 4  5  6  7]
 [ 8  9 10 11]]


In [10]:
var21 = np.array([[1,2,3,4],[5,6,7,8]])
varadd = np.multiply(var21,3)
print(varadd)

[[ 3  6  9 12]
 [15 18 21 24]]


In [11]:
var21 = np.array([[1,2,3,4],[5,6,7,8]])
varadd = np.reciprocal(var21)
print(varadd)

[[1 0 0 0]
 [0 0 0 0]]


In [12]:
var21 = np.array([[1,2,3,4],[5,6,7,8]])
var22 = np.array([[1,2,3,4],[5,6,7,8]])
varadd = np.multiply(var21,var22)
print(varadd)

[[ 1  4  9 16]
 [25 36 49 64]]


In [13]:
var21 = np.array([[1,2,3,4],[5,6,7,8]])
var22 = np.array([[1,2,3,4],[5,6,7,8]])
varadd = np.power(var21,var22)
print(varadd)

[[       1        4       27      256]
 [    3125    46656   823543 16777216]]
