zeros


In [3]:
import numpy as np
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))

print(ar_zero)              #printing 1 dim arr
print()                     #makes a gap btwn arrays
print(ar_zero1)             #prints 3x4 matrix


[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


ones

In [10]:
ar_one = np.ones(5)
ar_one1 = np.ones((5,4))
print(ar_one)
print()
print(ar_one1)

[1. 1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


empty array

In [11]:
ar_empty = np.empty(4)
print(ar_empty)

[0. 0. 0. 0.]


range array

In [12]:
ar_range = np.arange(10)
print(ar_range)


[0 1 2 3 4 5 6 7 8 9]


identity array

In [13]:
ar_diagonal = np.eye(4)
print(ar_diagonal)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [14]:
ar_diagonal = np.eye(3,8)
print(ar_diagonal)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]]


linspace

In [20]:
ar_lin = np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]
