# **RANDOM**

rand()

In [2]:
import numpy as np
var = np.random.rand(5)
print(var)

[0.37941607 0.67244887 0.8020892  0.71951432 0.30344765]


In [3]:
var1 = np.random.rand(5,5)
print(var1)

[[0.44747647 0.01276072 0.06610357 0.23634433 0.01637602]
 [0.71529532 0.8517994  0.51419047 0.26602308 0.39981004]
 [0.31582596 0.55334806 0.32983195 0.9314606  0.02623244]
 [0.70751567 0.01193555 0.83727066 0.75435409 0.14049998]
 [0.63943176 0.80233452 0.28491205 0.13819091 0.83110099]]


randn()

In [4]:
var2 = np.random.randn(5)
print(var2)

[-2.00726611  0.00295294  1.46033485  0.25708875 -0.65428511]


ranf()

In [6]:
var3 = np.random.ranf(5)
print(var3)


[0.48770955 0.19696685 0.97514065 0.12087003 0.90531979]


randint()


In [8]:
var4 = np.random.randint(5,20,5)
print(var4)

[12 17  6  9  5]
