SEARCH

In [6]:
import numpy as np
var = np.array([2,4,6,7,8,10])
x = np.where(( var%2 )== 0)
print(x)
print(var)

(array([0, 1, 2, 4, 5]),)
[ 2  4  6  7  8 10]


In [9]:
var = np.array([1,2,3,4,4,3,1,1,4,5])
x = np.searchsorted( var, 3)
print(x)
print(var)

2
[1 2 3 4 4 3 1 1 4 5]


SORT FUNCTION

In [10]:
var_1 = np.array([4,3,2,1,8,7,6,5])
print(np.sort(var_1))
print(var_1)

[1 2 3 4 5 6 7 8]
[4 3 2 1 8 7 6 5]


In [11]:
var_2 = np.array(["a","c","g","b","d"])
print(np.sort(var_2))
print(var_2)

['a' 'b' 'c' 'd' 'g']
['a' 'c' 'g' 'b' 'd']


FILTER ARRAY

In [13]:
var_3 = np.array([1,4,67,3,6,3,57])
f=[True,False,False,True,False,False,True]
new_a = var_3[f]
print(new_a)
print(type(new_a))

[ 1  3 57]
<class 'numpy.ndarray'>
