SHAPE

In [1]:
import numpy as np
var = np.array([[1,5],[5,9]])
print(var)
print()
print(var.shape)

[[1 5]
 [5 9]]

(2, 2)


In [10]:
var1 = np.array([1,2,3,4],ndmin= 4)
print(var1)
print(var1.ndim)
print()
print(var1.shape)

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


RESHAPE

In [11]:
var2 = np.array([1,3,5,7,9,3])
x = var2.reshape(2,3)
print(x)
print()
print(x.shape)
print(var2)

[[1 3 5]
 [7 9 3]]

(2, 3)
[1 3 5 7 9 3]


In [12]:
var3 = np.array([1,2,4,3,5,6,7,8,5,3,6,7])
print(var3)
print(var3.ndim)

print()
x1 = var3.reshape(6,2)
print(x1)
print(x1.ndim)

[1 2 4 3 5 6 7 8 5 3 6 7]
1

[[1 2]
 [4 3]
 [5 6]
 [7 8]
 [5 3]
 [6 7]]
2


In [13]:
var3 = np.array([1,2,4,3,5,6,7,8,5,3,6,7])
print(var3)
print(var3.ndim)

print()
x1 = var3.reshape(6,2)
print(x1)
print(x1.ndim)
x2 = x1.reshape(-1)
print(x2)
print(x2.ndim)


[1 2 4 3 5 6 7 8 5 3 6 7]
1

[[1 2]
 [4 3]
 [5 6]
 [7 8]
 [5 3]
 [6 7]]
2
[1 2 4 3 5 6 7 8 5 3 6 7]
1
